spring:

  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    #driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


  thymeleaf:
    suffix: .html
    cache: false
    mode: LEGACYHTML5

